apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-app
  namespace: vehicle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-app
  template:
    metadata:
      labels:
        app: vehicle-app
    spec:
      containers:
        - name: vehicle-app
          image: "{{ deploy_image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8282
          env:
            - name: SERVER_PORT
              value: "8282"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
