apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-app
  namespace: vehicle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-app
  template:
    metadata:
      labels:
        app: vehicle-app
    spec:
      containers:
        - name: vehicle-app
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 8282
          env:
            - name: SERVER_PORT
              value: "8282"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 40
            periodSeconds: 20
