apiVersion: v1
kind: Service
metadata:
  name: vehicle-svc
  namespace: vehicle
  labels:
    app: vehicle-app
spec:
  selector:
    app: vehicle-app
  ports:
    - name: http
      port: 8282
      targetPort: 8282
  type: LoadBalancer
