apiVersion: v1
kind: Service
metadata:
  name: vehicle-svc
  namespace: vehicle
spec:
  type: LoadBalancer
  selector:
    app: vehicle-app
  ports:
    - name: http
      port: 80
      targetPort: 8282
