INSERT INTO VEHICLE (VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE) VALUES ('CAR', 'Toyota', 'Sedan', 'Camry', 25000);
INSERT INTO VEHICLE (VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE) VALUES ('CAR', 'Honda', 'Sedan', 'Accord', 27000);
INSERT INTO VEHICLE (VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE) VALUES ('TRUCK', 'Ford', 'Pickup', 'F-150', 40000);
INSERT INTO VEHICLE (VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE) VALUES ('BIKE', 'Yamaha', 'Sport', 'R15', 18000);
