INSERT INTO VEHICLE (ID, VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE)
VALUES (1, 'CAR', 'Toyota', 'Sedan', 'Camry', 25000);
INSERT INTO VEHICLE (ID, VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE)
VALUES (2, 'CAR', 'Honda', 'Sedan', 'Accord', 27000);
INSERT INTO VEHICLE (ID, VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE)
VALUES (3, 'TRUCK', 'Ford', 'Pickup', 'F-150', 40000);
INSERT INTO VEHICLE (ID, VEHICLE_TYPE, NAME, TYPE, MODEL, PRICE)
VALUES (4, 'BIKE', 'Yamaha', 'Sport', 'R15', 18000);
